#version 430 core
layout(local_size_x = 16, local_size_y = 16) in;
layout(rgba8, binding = 0) uniform writeonly image2D uOutput;
layout(std430, binding = 0) readonly buffer Voxels { uint data[]; };
layout(std430, binding = 1) readonly buffer VoxelsCoarse { uint dataCoarse[]; };
layout(std430, binding = 2) readonly buffer VoxelsFar { uint dataFar[]; };

#include "uniforms.glsl"
#include "constants.glsl"
#include "sky_preetham.glsl"
#include "helpers.glsl"
#include "main_body.glsl"
